/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gourmentpizzas;

import java.io.FileWriter;
import java.io.IOException;
import javax.swing.JOptionPane;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

/**
 *
 * @author user
 */
public class OrderForm extends javax.swing.JFrame {

    /**
     * Creates new form OrderForm
     */
    public OrderForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jScrollPane1 = new javax.swing.JScrollPane();
        sizeTable = new javax.swing.JTable();
        orderFormTitleLabel = new javax.swing.JLabel();
        noteLabel = new javax.swing.JLabel();
        sauceRadioButton = new javax.swing.JRadioButton();
        bbqSauceLabel = new javax.swing.JLabel();
        extraCheeseLabel = new javax.swing.JLabel();
        cheeseRadioButton = new javax.swing.JRadioButton();
        additionalFillingsLabel = new javax.swing.JLabel();
        beefCheckBox = new javax.swing.JCheckBox();
        chickenCheckBox = new javax.swing.JCheckBox();
        pepperoniCheckBox = new javax.swing.JCheckBox();
        mushroomsCheckBox = new javax.swing.JCheckBox();
        sweetCornCheckBox = new javax.swing.JCheckBox();
        peppersCheckBox = new javax.swing.JCheckBox();
        chiliCheckBox = new javax.swing.JCheckBox();
        specialComboLabel = new javax.swing.JLabel();
        meatFeastCheckBox = new javax.swing.JCheckBox();
        veggieSpecialCheckBox = new javax.swing.JCheckBox();
        orderAnotherButton = new javax.swing.JButton();
        sizeLabel = new javax.swing.JLabel();
        sizeComboBox = new javax.swing.JComboBox<>();
        pizzaTypeLabel = new javax.swing.JLabel();
        pizzaTypeComboBox = new javax.swing.JComboBox<>();
        sumLabel = new javax.swing.JLabel();
        sumTextField = new javax.swing.JTextField();
        newPostCodeLabel = new javax.swing.JLabel();
        newMobileNumLabel = new javax.swing.JLabel();
        newNameTextField = new javax.swing.JTextField();
        newAddressTextField = new javax.swing.JTextField();
        newMobileNumTextField = new javax.swing.JTextField();
        newFormSaveButton = new javax.swing.JButton();
        newPostCodeTextField = new javax.swing.JTextField();
        newNameLabel = new javax.swing.JLabel();
        newStreetAddresLabel = new javax.swing.JLabel();
        calculateButton = new javax.swing.JButton();
        loadButton = new javax.swing.JButton();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        sizeTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Small (9 inch)", "£3.99", "£5.49"},
                {"Medium (12 inch)", "£5.99", "£7.99"},
                {"Large (15 inch)", "£8.99 ", "£11.99"}
            },
            new String [] {
                "Description", "Thin Crust", "Deep Pan"
            }
        ));
        jScrollPane1.setViewportView(sizeTable);

        orderFormTitleLabel.setText("Order Form");

        noteLabel.setText("Note: Pizzas come with tomato sauce and cheese as standard");

        sauceRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sauceRadioButtonActionPerformed(evt);
            }
        });

        bbqSauceLabel.setText("Please select if you want to replace tomato sauce with barbecue sauce (+50p) ");

        extraCheeseLabel.setText("Extra cheese (+50p)");

        cheeseRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cheeseRadioButtonActionPerformed(evt);
            }
        });

        additionalFillingsLabel.setText("Additional Fillings (+50p each)");

        beefCheckBox.setText("Beef");
        beefCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                beefCheckBoxActionPerformed(evt);
            }
        });

        chickenCheckBox.setText("Chicken");
        chickenCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chickenCheckBoxActionPerformed(evt);
            }
        });

        pepperoniCheckBox.setText("Pepperoni");
        pepperoniCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pepperoniCheckBoxActionPerformed(evt);
            }
        });

        mushroomsCheckBox.setText("Mushrooms");
        mushroomsCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mushroomsCheckBoxActionPerformed(evt);
            }
        });

        sweetCornCheckBox.setText("Sweetcorn");
        sweetCornCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sweetCornCheckBoxActionPerformed(evt);
            }
        });

        peppersCheckBox.setText("Peppers");
        peppersCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                peppersCheckBoxActionPerformed(evt);
            }
        });

        chiliCheckBox.setText("Chili");
        chiliCheckBox.setToolTipText("");
        chiliCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chiliCheckBoxActionPerformed(evt);
            }
        });

        specialComboLabel.setText("Special Combinations (+£1)");

        meatFeastCheckBox.setText("Meat feast: beef, chicken, pepperoni");
        meatFeastCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                meatFeastCheckBoxActionPerformed(evt);
            }
        });

        veggieSpecialCheckBox.setText("Veggie special: mushroom, sweetcorn, peppers");
        veggieSpecialCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                veggieSpecialCheckBoxActionPerformed(evt);
            }
        });

        orderAnotherButton.setText("Order another");
        orderAnotherButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orderAnotherButtonActionPerformed(evt);
            }
        });

        sizeLabel.setText("Size:");

        sizeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Small", "Medium", "Large" }));
        sizeComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sizeComboBoxActionPerformed(evt);
            }
        });

        pizzaTypeLabel.setText("Type");

        pizzaTypeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Thin Crust", "Deep Pan" }));
        pizzaTypeComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pizzaTypeComboBoxActionPerformed(evt);
            }
        });

        sumLabel.setText("Sum:");

        sumTextField.setText("    ");
        sumTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sumTextFieldActionPerformed(evt);
            }
        });

        newPostCodeLabel.setText("Post Code:");

        newMobileNumLabel.setText("Mobile Number:");

        newFormSaveButton.setText("Save");
        newFormSaveButton.setToolTipText("");
        newFormSaveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newFormSaveButtonActionPerformed(evt);
            }
        });

        newNameLabel.setText("Name:");

        newStreetAddresLabel.setText("Street Address:");

        calculateButton.setText("Calculate");
        calculateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculateButtonActionPerformed(evt);
            }
        });

        loadButton.setText("Load saved order");
        loadButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(newStreetAddresLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(newNameLabel)
                        .addComponent(newPostCodeLabel))
                    .addComponent(newMobileNumLabel)
                    .addComponent(orderFormTitleLabel)
                    .addComponent(noteLabel)
                    .addComponent(peppersCheckBox)
                    .addComponent(sweetCornCheckBox)
                    .addComponent(mushroomsCheckBox)
                    .addComponent(pepperoniCheckBox)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(bbqSauceLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(sauceRadioButton))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(extraCheeseLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cheeseRadioButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(additionalFillingsLabel)
                            .addComponent(beefCheckBox)
                            .addComponent(chickenCheckBox))
                        .addGap(60, 60, 60)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(specialComboLabel)
                            .addComponent(meatFeastCheckBox)
                            .addComponent(veggieSpecialCheckBox)))
                    .addComponent(chiliCheckBox)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(newAddressTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(newNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(newPostCodeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(newMobileNumTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(sizeLabel)
                                .addGap(18, 18, 18)
                                .addComponent(sizeComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(pizzaTypeLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(pizzaTypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(newFormSaveButton)
                        .addGap(18, 18, 18)
                        .addComponent(orderAnotherButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(loadButton)
                        .addGap(18, 18, 18)
                        .addComponent(calculateButton)
                        .addGap(12, 12, 12)
                        .addComponent(sumLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sumTextField)))
                .addGap(5, 5, 5))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(orderFormTitleLabel)
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newNameLabel)
                    .addComponent(newNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newPostCodeLabel)
                    .addComponent(newPostCodeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newStreetAddresLabel)
                    .addComponent(newAddressTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newMobileNumLabel)
                    .addComponent(newMobileNumTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(sizeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sizeLabel))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pizzaTypeLabel)
                            .addComponent(pizzaTypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addComponent(noteLabel)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bbqSauceLabel)
                    .addComponent(sauceRadioButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(extraCheeseLabel)
                    .addComponent(cheeseRadioButton))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(additionalFillingsLabel)
                    .addComponent(specialComboLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(beefCheckBox)
                    .addComponent(meatFeastCheckBox))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chickenCheckBox)
                    .addComponent(veggieSpecialCheckBox))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pepperoniCheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mushroomsCheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sweetCornCheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(peppersCheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chiliCheckBox)
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(orderAnotherButton)
                    .addComponent(sumLabel)
                    .addComponent(sumTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(newFormSaveButton)
                    .addComponent(calculateButton)
                    .addComponent(loadButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sauceRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sauceRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sauceRadioButtonActionPerformed

    private void mushroomsCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mushroomsCheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mushroomsCheckBoxActionPerformed

    private void beefCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_beefCheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_beefCheckBoxActionPerformed

    private void meatFeastCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_meatFeastCheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_meatFeastCheckBoxActionPerformed

    private void sizeComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sizeComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sizeComboBoxActionPerformed

    private void pizzaTypeComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pizzaTypeComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pizzaTypeComboBoxActionPerformed

    private void cheeseRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cheeseRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cheeseRadioButtonActionPerformed

    private void chickenCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chickenCheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chickenCheckBoxActionPerformed

    private void pepperoniCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pepperoniCheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pepperoniCheckBoxActionPerformed

    private void sweetCornCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sweetCornCheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sweetCornCheckBoxActionPerformed

    private void peppersCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_peppersCheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_peppersCheckBoxActionPerformed

    private void chiliCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chiliCheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chiliCheckBoxActionPerformed

    private void veggieSpecialCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_veggieSpecialCheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_veggieSpecialCheckBoxActionPerformed

    private void newFormSaveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newFormSaveButtonActionPerformed
        // TODO add your handling code here:                                                         //code to validate post code
        Pattern postalCodePattern = Pattern.compile("BN1|BN2|BN3[0-9][a-z]{2}", Pattern.CASE_INSENSITIVE); //https://www.w3schools.com/java/java_regex.asp
        Matcher match = postalCodePattern.matcher(newPostCodeTextField.getText());                        
        boolean matchFound = match.find();
        if (!matchFound) {
            newPostCodeTextField.setText("Invalid postal code, please try again.");
        }
                                                                                  //code to validate phone number
        Pattern numberPattern = Pattern.compile("0[0-9]{10}", Pattern.CASE_INSENSITIVE); //https://www.w3schools.com/java/java_regex.asp
        Matcher match2 = numberPattern.matcher(newMobileNumTextField.getText());
        boolean matchFound2 = match2.find();
        if (!matchFound2) {
            newMobileNumTextField.setText("Invalid number please try again.");
        }

        if (matchFound && matchFound2) {              //code to save user input into text file
            try {
                FileWriter myWriter = new FileWriter("newOrders.txt", true);   
                myWriter.write("\n" + newNameTextField.getText() + ", " + newAddressTextField.getText() + ", " + newPostCodeTextField.getText() + ", " + newMobileNumTextField.getText()
                        + ", " + sizeComboBox.getSelectedItem() + ", " + pizzaTypeComboBox.getSelectedItem() + ", " + "Tomato(True)/BBQ Sauce(False): " + sauceRadioButton.isSelected()
                        + ", " + "Extra cheese(True)/No extra cheese(False): " + cheeseRadioButton.isSelected() + ", " + "Beef: " + beefCheckBox.isSelected() + ", " + "Chicken: " + chickenCheckBox.isSelected()
                        + ", " + "Pepperoni: " + pepperoniCheckBox.isSelected() + ", " + "Mushrooms: " + mushroomsCheckBox.isSelected() + ", " + "Sweetcorn: " + sweetCornCheckBox.isSelected()
                        + ", " + "Peppers: " + peppersCheckBox.isSelected() + ", " + "Chili: " + chiliCheckBox.isSelected() + ", " + "MeatFeast: " + meatFeastCheckBox.isSelected()
                        + ", " + "VeggieSpecial: " + veggieSpecialCheckBox.isSelected() + ", " + sumTextField.getText() + "\r\n");

                myWriter.close();
            } catch (IOException e) {
                JOptionPane.showMessageDialog(null, e.toString(), "Alert", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_newFormSaveButtonActionPerformed

    private void sumTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sumTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sumTextFieldActionPerformed

    private void calculateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calculateButtonActionPerformed
        // TODO add your handling code here:'       //to calculate price of pizza
        double sum = 0;
        if (pizzaTypeComboBox.getSelectedItem().equals("Thin Crust") && sizeComboBox.getSelectedItem().equals("Small")) {
            sum = sum + 3.99;
        } else if (pizzaTypeComboBox.getSelectedItem().equals("Deep Pan") && sizeComboBox.getSelectedItem().equals("Small")) {
            sum = sum + 5.49;
        } else if (pizzaTypeComboBox.getSelectedItem().equals("Thin Crust") && sizeComboBox.getSelectedItem().equals("Medium")) {
            sum = sum + 5.99;
        } else if (pizzaTypeComboBox.getSelectedItem().equals("Deep Pan") && sizeComboBox.getSelectedItem().equals("Medium")) {
            sum = sum + 7.99;
        } else if (pizzaTypeComboBox.getSelectedItem().equals("Thin Crust") && sizeComboBox.getSelectedItem().equals("Large")) {
            sum = sum + 8.99;
        } else if (pizzaTypeComboBox.getSelectedItem().equals("Deep Pan") && sizeComboBox.getSelectedItem().equals("Large")) {
            sum = sum + 11.99;
        }

        if (cheeseRadioButton.isSelected()) {
            sum = sum + 0.5;
        }
        if (sauceRadioButton.isSelected()) {
            sum = sum + 0.5;
        }
        if (beefCheckBox.isSelected()) {
            sum = sum + 0.5;
        }
        if (chickenCheckBox.isSelected()) {
            sum = sum + 0.5;
        }
        if (pepperoniCheckBox.isSelected()) {
            sum = sum + 0.5;
        }
        if (mushroomsCheckBox.isSelected()) {
            sum = sum + 0.5;
        }
        if (sweetCornCheckBox.isSelected()) {
            sum = sum + 0.5;
        }
        if (peppersCheckBox.isSelected()) {
            sum = sum + 0.5;
        }
        if (chiliCheckBox.isSelected()) {
            sum = sum + 0.5;
        }
        if (meatFeastCheckBox.isSelected()) {
            sum = sum + 1;
        }
        if (veggieSpecialCheckBox.isSelected()) {
            sum = sum + 1;
        }

        String finalSum = Double.toString(sum);
        sumTextField.setText(finalSum);

    }//GEN-LAST:event_calculateButtonActionPerformed

    private void orderAnotherButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orderAnotherButtonActionPerformed
        // TODO add your handling code here:
        OrderForm orderForm1 = new OrderForm();
        orderForm1.setVisible(true);
    }//GEN-LAST:event_orderAnotherButtonActionPerformed

    private void loadButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadButtonActionPerformed
        // TODO add your handling code here:
        CheckIfExistingCustomerForm checkForm1 = new CheckIfExistingCustomerForm();
        checkForm1.setVisible(true);
    }//GEN-LAST:event_loadButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OrderForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OrderForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OrderForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OrderForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OrderForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel additionalFillingsLabel;
    private javax.swing.JLabel bbqSauceLabel;
    private javax.swing.JCheckBox beefCheckBox;
    private javax.swing.JButton calculateButton;
    private javax.swing.JRadioButton cheeseRadioButton;
    private javax.swing.JCheckBox chickenCheckBox;
    private javax.swing.JCheckBox chiliCheckBox;
    private javax.swing.JLabel extraCheeseLabel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JButton loadButton;
    private javax.swing.JCheckBox meatFeastCheckBox;
    private javax.swing.JCheckBox mushroomsCheckBox;
    private javax.swing.JTextField newAddressTextField;
    private javax.swing.JButton newFormSaveButton;
    private javax.swing.JLabel newMobileNumLabel;
    private javax.swing.JTextField newMobileNumTextField;
    private javax.swing.JLabel newNameLabel;
    private javax.swing.JTextField newNameTextField;
    private javax.swing.JLabel newPostCodeLabel;
    private javax.swing.JTextField newPostCodeTextField;
    private javax.swing.JLabel newStreetAddresLabel;
    private javax.swing.JLabel noteLabel;
    private javax.swing.JButton orderAnotherButton;
    private javax.swing.JLabel orderFormTitleLabel;
    private javax.swing.JCheckBox pepperoniCheckBox;
    private javax.swing.JCheckBox peppersCheckBox;
    private javax.swing.JComboBox<String> pizzaTypeComboBox;
    private javax.swing.JLabel pizzaTypeLabel;
    private javax.swing.JRadioButton sauceRadioButton;
    private javax.swing.JComboBox<String> sizeComboBox;
    private javax.swing.JLabel sizeLabel;
    private javax.swing.JTable sizeTable;
    private javax.swing.JLabel specialComboLabel;
    private javax.swing.JLabel sumLabel;
    private javax.swing.JTextField sumTextField;
    private javax.swing.JCheckBox sweetCornCheckBox;
    private javax.swing.JCheckBox veggieSpecialCheckBox;
    // End of variables declaration//GEN-END:variables
}
